export const PreloadTemplates = async function () {
    const tpl = CONFIG.gfl5r.paths.templates;
    return foundry.applications.handlebars.loadTemplates([
        // *** Actors : PC ***
        `${tpl}actors/character/approaches.html`,
        `${tpl}actors/character/attributes.html`,
        `${tpl}actors/character/conflict.html`,
        `${tpl}actors/character/disciplines.html`,
        `${tpl}actors/character/effects.html`,
        `${tpl}actors/character/identity.html`,
        `${tpl}actors/character/inventory.html`,
        `${tpl}actors/character/narrative.html`,
        `${tpl}actors/character/category.html`,
        `${tpl}actors/character/skill.html`,
        `${tpl}actors/character/social.html`,
        `${tpl}actors/character/status.html`,
        `${tpl}actors/character/stance.html`,
        `${tpl}actors/character/techniques.html`,
        // *** Actors : Character Builder ***
        `${tpl}actors/twelve-questions-dialog.html`,
        // *** Actors : NPC ***
        `${tpl}actors/npc/approaches.html`,
        `${tpl}actors/npc/attributes.html`,
        `${tpl}actors/npc/behaviors.html`,
        `${tpl}actors/npc/identity.html`,
        `${tpl}actors/npc/social.html`,
        `${tpl}actors/npc/skill.html`,
        `${tpl}actors/npc/summary.html`,
        // *** Actors : Vehicle ***
        `${tpl}actors/vehicle/stats.html`,
        `${tpl}actors/vehicle/passengers.html`,
        `${tpl}actors/vehicle/weapons.html`,
        `${tpl}actors/vehicle/description.html`,
        // *** Items ***
        `${tpl}items/armor/armors.html`,
        `${tpl}items/armor/armor-entry.html`,
        `${tpl}items/armor/armor-sheet.html`,
        `${tpl}items/item/items.html`,
        `${tpl}items/item/item-entry.html`,
        `${tpl}items/item/item-value.html`,
        `${tpl}items/item/item-sheet.html`,
        `${tpl}items/item/item-infos.html`,
        `${tpl}items/item/item-text-partial-reference.html`,
        `${tpl}items/item/item-text.html`,
        `${tpl}items/peculiarity/peculiarity-entry.html`,
        `${tpl}items/peculiarity/peculiarity-sheet.html`,
        `${tpl}items/peculiarity/peculiarity-text.html`,
        `${tpl}items/technique/technique-entry.html`,
        `${tpl}items/technique/technique-sheet.html`,
        `${tpl}items/technique/technique-text.html`,
        `${tpl}items/weapon/weapons.html`,
        `${tpl}items/weapon/weapon-entry.html`,
        `${tpl}items/weapon/weapon-sheet.html`,
        `${tpl}items/property/properties.html`,
        `${tpl}items/property/property-entry.html`,
        `${tpl}items/discipline/discipline-sheet.html`,
        `${tpl}items/discipline/discipline-text.html`,
    ]);
};
